#!/usr/bin/env bash
# Bootstraps all AWS resources the microservices expect.
# Runs inside the LocalStack container after services are ready.
set -euo pipefail

REGION="${AWS_DEFAULT_REGION:-us-east-1}"
ACCOUNT_ID="000000000000"
IDS_FILE="/etc/localstack/init/ready.d/ids.env"

if [ -f "$IDS_FILE" ]; then
  echo "[bootstrap] ids.env already exists — resources already provisioned, skipping."
  exit 0
fi

echo "[bootstrap] creating SQS queues..."
awslocal sqs create-queue --queue-name app-events >/dev/null
awslocal sqs create-queue --queue-name appointment-events >/dev/null
awslocal sqs create-queue --queue-name notification-jobs >/dev/null
awslocal sqs create-queue --queue-name payment-success >/dev/null
awslocal sqs create-queue --queue-name payment-failed >/dev/null

echo "[bootstrap] creating SNS topic..."
NOTIF_TOPIC_ARN="$(awslocal sns create-topic --name notifications --query 'TopicArn' --output text)"

echo "[bootstrap] subscribing notification-jobs queue to notifications topic..."
NOTIF_QUEUE_URL="$(awslocal sqs get-queue-url --queue-name notification-jobs --query 'QueueUrl' --output text)"
NOTIF_QUEUE_ARN="$(awslocal sqs get-queue-attributes --queue-url "$NOTIF_QUEUE_URL" --attribute-names QueueArn --query 'Attributes.QueueArn' --output text)"
awslocal sns subscribe --topic-arn "$NOTIF_TOPIC_ARN" --protocol sqs --notification-endpoint "$NOTIF_QUEUE_ARN" >/dev/null

echo "[bootstrap] creating Cognito User Pool..."
USER_POOL_ID="$(awslocal cognito-idp create-user-pool \
  --pool-name prod-config-pool \
  --auto-verified-attributes email \
  --policies 'PasswordPolicy={MinimumLength=8,RequireUppercase=false,RequireLowercase=false,RequireNumbers=false,RequireSymbols=false}' \
  --query 'UserPool.Id' --output text)"

USER_POOL_CLIENT_ID="$(awslocal cognito-idp create-user-pool-client \
  --user-pool-id "$USER_POOL_ID" \
  --client-name prod-config-client \
  --no-generate-secret \
  --explicit-auth-flows ALLOW_USER_PASSWORD_AUTH ALLOW_REFRESH_TOKEN_AUTH \
  --query 'UserPoolClient.ClientId' --output text)"

echo "[bootstrap] seeding test user (test@example.com / Test1234)..."
awslocal cognito-idp admin-create-user \
  --user-pool-id "$USER_POOL_ID" \
  --username test@example.com \
  --user-attributes Name=email,Value=test@example.com Name=email_verified,Value=true \
  --message-action SUPPRESS >/dev/null
awslocal cognito-idp admin-set-user-password \
  --user-pool-id "$USER_POOL_ID" \
  --username test@example.com \
  --password Test1234 \
  --permanent >/dev/null

echo "[bootstrap] creating ECR repositories (for terraform-driven Fargate deploys)..."
for repo in prod-config-auth-repo prod-config-core-repo prod-config-notification-repo; do
  awslocal ecr create-repository --repository-name "$repo" >/dev/null 2>&1 || true
done

echo "[bootstrap] writing IDs to $IDS_FILE..."
cat >"$IDS_FILE" <<EOF
# Generated by 00-bootstrap.sh — sourced by docker-compose via env_file
COGNITO_USER_POOL_ID=$USER_POOL_ID
COGNITO_USER_POOL_CLIENT_ID=$USER_POOL_CLIENT_ID
SNS_TOPIC_ARN=$NOTIF_TOPIC_ARN
SQS_APP_EVENTS_URL=http://localstack:4566/${ACCOUNT_ID}/app-events
SQS_NOTIFICATION_JOBS_URL=$NOTIF_QUEUE_URL
AWS_SQS_PAYMENT_SUCCESS_QUEUE_URL=http://localstack:4566/${ACCOUNT_ID}/payment-success
AWS_SQS_PAYMENT_FAILED_QUEUE_URL=http://localstack:4566/${ACCOUNT_ID}/payment-failed
EOF

echo "[bootstrap] done. IDs:"
cat "$IDS_FILE"
